name: traveler_pg

services:
  db:
    image: postgres:18
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - traveler_pgdata:/var/lib/postgresql
      - ./jobs_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro

volumes:
  traveler_pgdata: